# @name get-prompts
GET http://localhost:3333/prompts

###

# @name upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="new-example.mp3"
Content-Type: audio/mpeg

< ./new-example.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription
POST http://localhost:3333/videos/b23192bc-cdf9-4ef3-85bf-773bb2f76c4f/transcription
Content-Type: application/json

{
    "prompt": "neymar falando, jogador de futebol, paulo henrique ganso"
}


###

# @name generate-ai-completion
POST http://localhost:3333/ai/complete
Content-Type: application/json

{
    "videoId": "b23192bc-cdf9-4ef3-85bf-773bb2f76c4f",
    "template": "Gere um resumo sucinto da transcrição do vídeo informada a seguir: '''{transcription}'''",
    "temperature": 0.5
}

